SystemOrganization addCategory: #'OP-UML-BootstrapGenerator'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Bootstrap-Generator'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Metamodel-Generator'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Profile-Generator'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Reader'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Templates'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Tests'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Utilities'!
