SystemOrganization addCategory: #'OP-UML-BootstrapGenerator'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Bootrap-Generator'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Metamodel-Generator'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-OPUMLMetamodelGeneratorTemplates'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Reader'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Templates'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Tests'!
SystemOrganization addCategory: 'OP-UML-BootstrapGenerator-Utilities'!
