"
I store metadata for the OpenPonk-UML-BootstrapGenerator package. This package contains the infrastructure and code generators required to parse OMG UML XMI specifications and emit the fully functional Pharo UML metamodel implementation.
"
Class {
	#name : 'ManifestOpenPonkUMLBootstrapGenerator',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-UML-BootstrapGenerator-Manifest',
	#package : 'OpenPonk-UML-BootstrapGenerator',
	#tag : 'Manifest'
}
