"
I provide the Pharo implementation logic for checking boundary constraints and computing lower/upper bounds for UML MultiplicityElements during the bootstrap generation phase.
"
Class {
	#name : 'OPUMLBootMultiplicityBehaviorImplementation',
	#superclass : 'Object',
	#category : 'OpenPonk-UML-BootstrapGenerator-Metamodel-Generator',
	#package : 'OpenPonk-UML-BootstrapGenerator',
	#tag : 'Metamodel-Generator'
}
